name: Mice-BotEvade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - pillow
  - jupyterlab
  - pytorch
  - pygame
  - pytest
  - pyyaml
  - shapely
  - tensorboard
  - jsonschema
  - pip:
      - cellworld==0.0.381
      - cellworld-belief==0.0.33
      - gymnasium==0.28.1
      - pulsekit==0.0.3
      - stable-baselines3==2.3.2
