"""Reward functions for the point-mass environments.

Rewards intentionally consume named transition terms rather than the flattened
and frame-stacked observation.  The latter is a policy input whose layout can
change when fields are added to an environment; it is not a stable reward API.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any


def _named_reward_terms(source: Any) -> Mapping[str, Any]:
    """Return a named reward-term mapping and fail loudly on flat arrays.

    The environment passes a mapping directly.  Accepting a nested
    ``reward_terms`` mapping and an object with named attributes keeps the
    reward functions convenient to use in small unit tests, while deliberately
    refusing to infer fields from ndarray positions.
    """

    if isinstance(source, Mapping):
        nested = source.get("reward_terms")
        if isinstance(nested, Mapping):
            return nested
        return source

    nested = getattr(source, "reward_terms", None)
    if isinstance(nested, Mapping):
        return nested

    if source is not None and all(
        hasattr(source, field)
        for field in ("puffed", "prey_goal_distance")
    ):
        terms = {
            "capture": getattr(source, "puffed"),
            "goal_distance": getattr(source, "prey_goal_distance"),
        }
        if hasattr(source, "goal_achieved"):
            terms["goal_achieved"] = getattr(source, "goal_achieved")
        return terms

    raise TypeError(
        "Reward functions require named reward_terms; a flattened observation "
        "array is not a valid reward input"
    )


def _term(terms: Mapping[str, Any], name: str, *aliases: str, default: Any = None) -> Any:
    """Read one named term, allowing only explicit semantic aliases."""

    if name in terms:
        return terms[name]
    for alias in aliases:
        if alias in terms:
            return terms[alias]
    if default is not None:
        return default
    raise KeyError(f"Missing named reward term: {name!r}")


# ── BotEvade reward ──────────────────────────────────────────────────────────

def custom_reward(reward_terms) -> float:
    """Reward a single BotEvade transition.

    ``capture`` and ``goal_achieved`` are transition-level terms generated by
    the environment from the model state.  In particular, ``capture`` is a
    one-step event and cannot be confused with ``time_prey_seen_predator``.
    """

    terms = _named_reward_terms(reward_terms)
    capture = float(_term(terms, "capture", "capture_event", "puffed", default=0.0))
    goal_achieved = float(_term(terms, "goal_achieved", "goal_event", default=0.0))
    return -1.0 * capture + 1.0 * goal_achieved


# ── Oasis reward ─────────────────────────────────────────────────────────────
#
# Reward design:
#   +1.0   each time a goal transition event is emitted
#   -1.0   each capture transition event
#   -0.05 * prey_goal_distance   dense shaping toward current goal
#   +3.0   episode completion bonus

def oasis_reward():
    """Return a reward function for ``OasisEnv``.

    Goal completion is supplied as the named ``goal_event``/
    ``goal_achieved`` term by the environment.  No stateful comparison of
    ``goals_remaining`` is needed, so the reward remains correct if the
    observation field order or stacking configuration changes.
    """

    def _reward(reward_terms) -> float:
        terms = _named_reward_terms(reward_terms)
        capture = float(_term(terms, "capture", "capture_event", "puffed", default=0.0))
        goal_event = float(_term(terms, "goal_achieved", "goal_event", default=0.0))
        goal_distance = float(
            _term(terms, "goal_distance", "prey_goal_distance", default=0.0)
        )
        finished = float(_term(terms, "finished", default=0.0))

        return (
            goal_event
            - capture
            - 0.05 * goal_distance
            + 3.0 * finished
        )

    return _reward
